#%RAML 0.8


title: Batch Processor
securedBy: [basic]
traits:
  - paged:
      queryParameters:
        size:
          description: The total number of pages to return
          type: number
          required: false
        page:
          description: The offset of pages to return
          type: number
          required: false
securitySchemes:
  - basic:
      description: |
        Supports Basic Authentication (RFC2617) for authenticating all API requests
      type: Basic Authentication
      describedBy:
        headers:
            Authorization:
              description: |
                 Used to send a username and password encoded token
              type: string
              example: Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ==
        responses:
          401:
            description: Bad or expired token.
          403:
            description: Unauthorized request.

/batch: !include batch.raml

/batches: !include batches.raml
