displayName: Batch job collection details
/:
  get:
    description: Get a list of batches.
    queryParameters:
      batchIds:
        description: Comma separated list of batch ids
        example: 134,142
    responses:
      200:
        body:
          application/json:
            example: |
              {
                data: [
                  {
                    "id": "134",
                    "createTime": "2014-05-23T10:35:00Z",
                    "updateTime": "2014-06-13T10:38:00Z",
                    "endTime": "2014-06-13T10:45:00Z",
                    "totalCount": 255000,
                    "errorCount": 0,
                    "successCount": 255000
                  },
                  {
                    "id": "142",
                    "createTime": "2014-06-13T10:35:00Z",
                    "updateTime": "2014-06-13T10:38:00Z",
                    "endTime": "2014-06-13T10:45:00Z",
                    "totalCount": 3200,
                    "errorCount": 0,
                    "successCount": 12632
                  }
                ]
              }
