displayName: Individual Batch job details
/{batchId}:
  get:
    description: Returns all the information for the specified batch id
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "id": "42",
                "status": "COMPLETE",
                "createTime": "2015-02-16T13:23:00Z",
                "updateTime": "2014-05-23T10:36:14Z",
                "endTime": "2014-05-23T10:36:14Z",
                "successCount": 10,
                "errorCount": 1,
                "totalCount": 11,
                "categoryCounts": {
                  "created": 3,
                  "updated": 4,
                  "deleted": 3
                }
              }
  /items:
    get:
      description: Get a list of batch items.
      is: [ paged ]
      queryParameters:
        status:
          description: Filter items by status.
          enum: [ "SUCCESS", "ERROR" ]
          required: false
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "page": 1,
                  "size": 20,
                  "total": 2,
                  "data": [
                    {
                      "batchId": "134",
                      "itemNumber": 1,
                      "status": "SUCCESS",
                      "createTime": "2014-05-23T10:35:00Z",
                      "updateTime": "2014-05-23T10:36:14Z",
                      "category": "new-profile",
                      "message": null
                    },
                    {
                      "batchId": "134",
                      "itemNumber": 2,
                      "status": "ERROR",
                      "createTime": "2014-05-23T10:35:00Z",
                      "updateTime": "2014-05-23T10:36:14Z",
                      "category": null,
                      "message": "Missing required email address"
                    }
                  ]
                }
  /errorfile:
    get:
      description: Get a list of batch items errors ziped.
      responses:
        200:
          body:
            application/zip:
        404:
          description: BatchId not found
        409:
          description: Processing for this BatchId is not yet completed
